spring.application.name=test-site-spring-boot-htmx

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://localhost:5432/benchmark
spring.datasource.username=benchmark
spring.datasource.password=benchmark

spring.jpa.show-sql=true
spring.data.web.pageable.one-indexed-parameters=true

spring.jpa.hibernate.ddl-auto=update

server.tomcat.relaxed-query-chars=[,],{,}

server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/css,application/javascript,text/javascript,application/json,image/svg+xml
server.compression.min-response-size=1024
